### FOR CREATION OF ADMIN 
### IF YOU DON'T HAVE AN ADMIN YET.. PLEASE DO THIS FIRST    
### Remove first the authenticateToken at index.js in librarianRoute
### Go to controllers > librarian > users.controller.js
### Comment the If else condition  |from line 44 up to line 50, and line 73| |To comment 'CTRL+/'|
### Click Send Request
### Undo 'CTRL+Z' file in index.js and controllers > librarian > users.controller.js
### Proceed to Login 

POST http://localhost:3600/api/v1/librarian/users
Content-Type: application/json

{
    "idNumber":"2018-00012-CM-0",
    "email": "librarian@gmail.com",
    "password": "admin",
    "firstName": "Librarian",
    "lastName": "Admin",
    "contactNumber": "09127355978",
    "gender":"Others",
    "userType": "Librarian",
    "status": "Active"
}


### FOR LOGIN
### just click Send Request if you're logging in the admin
### if not admin, change the value of columns email and password

POST http://localhost:3600/api/v1/home/login
Content-Type: application/json

{
    "email": "librarian@gmail.com",
    "password": "admin"
}



### Find specific record
GET http://localhost:3600/api/v1/librarian/materials/593fc725-9fbc-4f5c-a6f1-7d8b6ca37d17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyZDlmNmU4MS1iMGI3LTQzNzYtODgxMC1iZmNmNjMyNjU3NDUiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyNDkwMzE4MCwiZXhwIjoxNjI0OTEzOTgwfQ.ciwLgZxTiu7J9RmK1arfGwP5qSl9ouyQdGg05x0h36s



### FOR CREATE     |don't forget to change the path before send request|
### Check the path at routes folder
### login first to get the token then paste and replace the sample token
### change the example column and value depends on the what you want to create

POST http://localhost:3600/api/v1/librarian/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyZDlmNmU4MS1iMGI3LTQzNzYtODgxMC1iZmNmNjMyNjU3NDUiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyNDkwMzE4MCwiZXhwIjoxNjI0OTEzOTgwfQ.ciwLgZxTiu7J9RmK1arfGwP5qSl9ouyQdGg05x0h36s
Content-Type: application/json

{
    "standardType": "ISBN",
    "standardNumber": "978-0-06-199227-8",
    "title": "The One and Only Ivan",
    "author_materials":[
        {
            "authorID": "bfbec48b-925b-4f16-bc6c-61a170fd7955"
        }
    ],
    "genre_materials":[
        {
            "genreID": "518e1482-d989-42a0-ab10-27266d3bdd10"
        },
        {
            "genreID": "746ed845-9cea-43b3-9a9c-95f58c42e728"
        },
        {
            "genreID": "4cb815ff-097d-4fd1-9966-b20fdfc77d44"
        }
    ],
    "format": "Paperback",
    "pageNo": "336",
    "volumeNo": "",
    "edition": "",
    "editionYear": "",
    "seriesYear": "",
    "dateOfPublication": "2012-01-17",
    "description":"This unforgettable novel from renowned author Katherine Applegate celebrates the transformative power of unexpected friendship. Inspired by the true story of a captive gorilla known as Ivan, this illustrated book is told from the point of view of Ivan himself. Having spent twenty-seven years behind the glass walls of his enclosure in a shopping mall, Ivan has grown accustomed to humans watching him. He hardly ever thinks about his life in the jungle. Instead, Ivan occupies himself with television, his friends Stella and Bob, and painting. But when he meets Ruby, a baby elephant taken from the wild, he is forced to see their home, and his art, through new eyes.",
    "status": "Active",
    "shelfID":"4011678b-d51a-4717-a1d7-7caae6947191",
    "languageID":"b34925bd-7857-4ff7-875e-5b2e41f21564",
    "typeID":"2cf304c1-f30f-4aa7-bec9-0c8fcf828f1e",
    "publisherID":"99c7c760-dc7e-4a51-9fdb-e5dcd1d8bbec",
    "pubCountryID":"69c059cc-1491-413e-9f7e-f9656ebe9306"
}



### FOR UPDATE     |don't forget to change the path before send request|
### Check the path at routes folder
### login first to get the token then paste and replace the sample token
### id of the record you want to update is required   |ID located at the end of path|

PUT http://localhost:3600/api/v1/librarian/rooms/e733c99c-fd11-45fa-bdaf-5292d0fdb8e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyZDlmNmU4MS1iMGI3LTQzNzYtODgxMC1iZmNmNjMyNjU3NDUiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyNTA2NTkzOSwiZXhwIjoxNjI1MDc2NzM5fQ.oJ8aTK1zMCxcdq9l9pji0uH1ygOCk3qlUxFYDi3M9P8
Content-Type: application/json

{
    "status":"Inactive"
}



### Change Status of record into Inactive
DELETE http://localhost:3600/api/v1/librarian/material_types/4cb08e50-652c-44f7-8fc7-d5a0af4b7044
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmZmU2ZDJjZC1jNmFjLTRhYjQtOTRlZi0xMDQ5MzkyMjhiYWYiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyNDM4NTUwNywiZXhwIjoxNjI0MzkyNzA3fQ.W4P-l5ml_2yJalJcdtupsMDEbta7fSNjInNE64iBezs



###test
POST http://localhost:3600/api/v1/librarian/copies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyZDlmNmU4MS1iMGI3LTQzNzYtODgxMC1iZmNmNjMyNjU3NDUiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyNTA2NTkzOSwiZXhwIjoxNjI1MDc2NzM5fQ.oJ8aTK1zMCxcdq9l9pji0uH1ygOCk3qlUxFYDi3M9P8
Content-Type: application/json

{
    "copyNumber":"COPYID-04",
    "status":"Available",
    "materialID": "593fc725-9fbc-4f5c-a6f1-7d8b6ca37d17"
}

###

POST http://localhost:3600/api/v1/librarian/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyZDlmNmU4MS1iMGI3LTQzNzYtODgxMC1iZmNmNjMyNjU3NDUiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyNTA2NTkzOSwiZXhwIjoxNjI1MDc2NzM5fQ.oJ8aTK1zMCxcdq9l9pji0uH1ygOCk3qlUxFYDi3M9P8
Content-Type: application/json

{
    "borrowDate":"2021-07-20",
    "userID": "b6002375-7476-4b52-a692-c606e0887bf8",
    "material_borrow_records":[
        {
            "dueDate": "2021-07-30",
            "status": "Unreturned",
            "copyID": "5920058d-e92c-4971-95f6-cace78e82ee9"
        }
    ]
}


### FOR GET    |don't forget to change the path before send request|
### Check the path at routes folder
### login first to get the token then paste and replace the sample token
### change the example column and value depends on the what you want to create

GET http://localhost:3600/api/v1/librarian/publishers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyZDlmNmU4MS1iMGI3LTQzNzYtODgxMC1iZmNmNjMyNjU3NDUiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyNTE5NjExMywiZXhwIjoxNjI1MjA2OTEzfQ.hJUm7JAk1LGp-1tqzBdPiXbXRV1Nb0Gcr8aRLva9eeQ