### FOR CREATION OF ADMIN 
### IF YOU DON'T HAVE AN ADMIN YET.. PLEASE DO THIS FIRST    
### Remove first the authenticateToken at index.js in librarianRoute
### Go to controllers > librarian > users.controller.js
### Comment the If else condition  |from line 44 up to line 50, and line 73| |To comment 'CTRL+/'|
### Click Send Request
### Undo 'CTRL+Z' file in index.js and controllers > librarian > users.controller.js
### Proceed to Login 

POST http://localhost:3600/api/v1/librarian/users
Content-Type: application/json

{
    "idNumber":"2018-00012-CM-0",
    "email": "librarian@gmail.com",
    "password": "admin",
    "firstName": "Librarian",
    "lastName": "Admin",
    "contactNumber": "09127355978",
    "gender":"Others",
    "userType": "Librarian",
    "status": "Active"
}



### FOR LOGIN
### just click Send Request if you're logging in the admin
### if not admin, change the value of columns email and password

POST http://localhost:3600/api/v1/home/login
Content-Type: application/json

{
    "email": "librarian@gmail.com",
    "password": "admin"
}



### FOR GET    |don't forget to change the path before send request|
### Check the path at routes folder
### login first to get the token then paste and replace the sample token
### change the example column and value depends on the what you want to create

GET http://localhost:3600/api/v1/librarian/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmZmU2ZDJjZC1jNmFjLTRhYjQtOTRlZi0xMDQ5MzkyMjhiYWYiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyMzc2NjE1OSwiZXhwIjoxNjIzNzczMzU5fQ.LBcjzWdivXmtimoGAq6fxhpOF5J4wMNMCaxTI6eIbfU



### FOR CREATE     |don't forget to change the path before send request|
### Check the path at routes folder
### login first to get the token then paste and replace the sample token
### change the example column and value depends on the what you want to create

POST http://localhost:3600/api/v1/librarian/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmZmU2ZDJjZC1jNmFjLTRhYjQtOTRlZi0xMDQ5MzkyMjhiYWYiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyMzc2NjE1OSwiZXhwIjoxNjIzNzczMzU5fQ.LBcjzWdivXmtimoGAq6fxhpOF5J4wMNMCaxTI6eIbfU
Content-Type: application/json

{
    "standardType": "ISBN",
    "standardNumber": "978-0-06-199227-8",
    "title": "The One and Only Ivan",
    "format": "Paperback",
    "pageNo": "336",
    "volumeNo": "",
    "edition": "",
    "editionYear": "",
    "seriesYear": "",
    "dateOfPublication": "2015-01-06",
    "status": "Active",
    "shelfID":"3a97ed0b-7b45-4169-af1e-f4fc222b34c7",
    "languageID":"f57be3a3-4b0e-454d-b90b-854b71de9aa3",
    "typeID":"4cb08e50-652c-44f7-8fc7-d5a0af4b7044",
    "publisherID":"8f57648a-84d2-484a-a67a-5a8bf6869aea",
    "pubCountryID":"51c00c7c-eb96-47b2-bab3-3606966601bd",
    "authors": [{
            "authorFirstName":"Katherine",
            "authorLastName": "Applegate",
            "status":"Active"
        },
        {
            "authorFirstName":"Patricia",
            "authorLastName": "Castelao",
            "status":"Active"
        }],
    "genres": [{
            "genre":"Novel",
            "status":"Active"
        }]
}



### FOR UPDATE     |don't forget to change the path before send request|
### Check the path at routes folder
### login first to get the token then paste and replace the sample token
### id of the record you want to update is required   |ID located at the end of path|

PUT http://localhost:3600/api/v1/librarian/rooms/bce5407f-410b-470b-b440-a47fe51d71fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmZmU2ZDJjZC1jNmFjLTRhYjQtOTRlZi0xMDQ5MzkyMjhiYWYiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyMzc2NjE1OSwiZXhwIjoxNjIzNzczMzU5fQ.LBcjzWdivXmtimoGAq6fxhpOF5J4wMNMCaxTI6eIbfU
Content-Type: application/json

{
    "roomName":"Room 101"
}


POST http://localhost:3600/api/v1/librarian/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmZmU2ZDJjZC1jNmFjLTRhYjQtOTRlZi0xMDQ5MzkyMjhiYWYiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyMzc2NjE1OSwiZXhwIjoxNjIzNzczMzU5fQ.LBcjzWdivXmtimoGAq6fxhpOF5J4wMNMCaxTI6eIbfU
Content-Type: application/json

###test
POST http://localhost:3600/api/v1/librarian/shelves
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmZmU2ZDJjZC1jNmFjLTRhYjQtOTRlZi0xMDQ5MzkyMjhiYWYiLCJ1c2VyVHlwZSI6IkxpYnJhcmlhbiIsImVtYWlsIjoibGlicmFyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTYyMzc2NjE1OSwiZXhwIjoxNjIzNzczMzU5fQ.LBcjzWdivXmtimoGAq6fxhpOF5J4wMNMCaxTI6eIbfU
Content-Type: application/json

{
    "shelfName":"Children's Book",
    "status": "Active",
    "roomID":"50d7d511-c1b3-4d9d-a5e8-25615b7d851a"
}